#!/usr/bin/env bash

set -e

# Parse command line arguments
JSON_MODE=false
ARGS=()

for arg in "$@"; do
    case "$arg" in
        --json) 
            JSON_MODE=true 
            ;;
        --help|-h) 
            echo "Usage: $0 [--json]"
            echo "  --json    Output results in JSON format"
            echo "  --help    Show this help message"
            exit 0 
            ;;
        *) 
            ARGS+=("$arg") 
            ;;
    esac
done

# Get script directory and load common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Get all paths and variables from common functions
eval $(get_feature_paths)

# Check if we're on a proper feature branch (only for git repos)
check_feature_branch "$CURRENT_BRANCH" "$HAS_GIT" || exit 1

# Ensure the design directory structure exists
mkdir -p "$DESIGN_DIR"
mkdir -p "$DESIGN_DIR/components"
mkdir -p "$DESIGN_DIR/wireframes"

# Output file paths
OVERVIEW_FILE="$DESIGN_DIR/overview.md"
SUMMARY_FILE="$DESIGN_DIR/summary.md"
VISUAL_DESIGN_FILE="$DESIGN_DIR/visual-design.md"
INTERACTION_DESIGN_FILE="$DESIGN_DIR/interaction-design.md"
COMPONENTS_DIR="$DESIGN_DIR/components"
WIREFRAMES_DIR="$DESIGN_DIR/wireframes"

# Template file paths
OVERVIEW_TEMPLATE="$REPO_ROOT/.arckit/templates/design-overview-template.md"
SUMMARY_TEMPLATE="$REPO_ROOT/.arckit/templates/design-summary-template.md"
VISUAL_DESIGN_TEMPLATE="$REPO_ROOT/.arckit/templates/design-visual-template.md"
INTERACTION_DESIGN_TEMPLATE="$REPO_ROOT/.arckit/templates/design-interaction-template.md"
COMPONENT_TEMPLATE="$REPO_ROOT/.arckit/templates/design-component-template.md"
WIREFRAME_PAGE_TEMPLATE="$REPO_ROOT/.arckit/templates/design-wireframe-page-template.html"

# Note: All files are generated by AI from templates in the design command
# This script only sets up directories and outputs paths

# Output results
if $JSON_MODE; then
    printf '{"DESIGN_DIR":"%s","OVERVIEW_FILE":"%s","SUMMARY_FILE":"%s","VISUAL_DESIGN_FILE":"%s","INTERACTION_DESIGN_FILE":"%s","COMPONENTS_DIR":"%s","WIREFRAMES_DIR":"%s","OVERVIEW_TEMPLATE":"%s","SUMMARY_TEMPLATE":"%s","VISUAL_DESIGN_TEMPLATE":"%s","INTERACTION_DESIGN_TEMPLATE":"%s","COMPONENT_TEMPLATE":"%s","WIREFRAME_PAGE_TEMPLATE":"%s","FEATURE_SPEC":"%s","BRANCH":"%s","HAS_GIT":"%s"}\n' \
        "$DESIGN_DIR" "$OVERVIEW_FILE" "$SUMMARY_FILE" "$VISUAL_DESIGN_FILE" "$INTERACTION_DESIGN_FILE" "$COMPONENTS_DIR" "$WIREFRAMES_DIR" "$OVERVIEW_TEMPLATE" "$SUMMARY_TEMPLATE" "$VISUAL_DESIGN_TEMPLATE" "$INTERACTION_DESIGN_TEMPLATE" "$COMPONENT_TEMPLATE" "$WIREFRAME_PAGE_TEMPLATE" "$FEATURE_SPEC" "$CURRENT_BRANCH" "$HAS_GIT"
else
    echo "DESIGN_DIR: $DESIGN_DIR"
    echo "OVERVIEW_FILE: $OVERVIEW_FILE"
    echo "SUMMARY_FILE: $SUMMARY_FILE"
    echo "VISUAL_DESIGN_FILE: $VISUAL_DESIGN_FILE"
    echo "INTERACTION_DESIGN_FILE: $INTERACTION_DESIGN_FILE"
    echo "COMPONENTS_DIR: $COMPONENTS_DIR"
    echo "WIREFRAMES_DIR: $WIREFRAMES_DIR"
    echo "OVERVIEW_TEMPLATE: $OVERVIEW_TEMPLATE"
    echo "SUMMARY_TEMPLATE: $SUMMARY_TEMPLATE"
    echo "VISUAL_DESIGN_TEMPLATE: $VISUAL_DESIGN_TEMPLATE"
    echo "INTERACTION_DESIGN_TEMPLATE: $INTERACTION_DESIGN_TEMPLATE"
    echo "COMPONENT_TEMPLATE: $COMPONENT_TEMPLATE"
    echo "WIREFRAME_PAGE_TEMPLATE: $WIREFRAME_PAGE_TEMPLATE"
    echo "FEATURE_SPEC: $FEATURE_SPEC"
    echo "BRANCH: $CURRENT_BRANCH"
    echo "HAS_GIT: $HAS_GIT"
fi

